name: dotnet build & test

on: [push]

jobs:
  build:

    runs-on: windows-latest 
    strategy:
      matrix:
        include:
        - dotnet-version: '3.1.x'
          tfm: 'netcoreapp3.1'

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: dotnet restore -p:TargetFramework=${{ matrix.tfm }}
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-restore --verbosity normal -f="${{ matrix.tfm }}"

